// <auto-generated />
using System;
using CaseFlow.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseFlow.Server.Migrations
{
    [DbContext(typeof(CaseFlowDbContext))]
    partial class CaseFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseFlow.Server.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_name");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("AttachmentId")
                        .HasName("attachments_pkey");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "idx_attach_entity")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "UploadedBy" }, "idx_attach_uploader")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "Action", "CreatedAt" }, "idx_audit_action")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CaseId" }, "idx_audit_case")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "idx_audit_entity")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_audit_user")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CaseId"));

                    b.Property<int?>("AssignedPmId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_pm_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_by");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("case_number");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("case_type")
                        .HasDefaultValueSql("'REPAIR'::character varying");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("integer")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority")
                        .HasDefaultValueSql("'MEDIUM'::character varying");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int?>("RelatedCaseId")
                        .HasColumnType("integer")
                        .HasColumnName("related_case_id");

                    b.Property<string>("RelationType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relation_type");

                    b.Property<string>("ReporterEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("reporter_email");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reporter_name");

                    b.Property<string>("ReporterPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reporter_phone");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)10)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("total_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CaseId")
                        .HasName("cases_pkey");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RelatedCaseId");

                    b.HasIndex(new[] { "CaseNumber" }, "cases_case_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "AssignedPmId" }, "idx_cases_assigned_pm")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CategoryId" }, "idx_cases_category")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_cases_created_at")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CreatedBy" }, "idx_cases_created_by")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CustomerId" }, "idx_cases_customer")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Priority" }, "idx_cases_priority")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "ProjectId", "CreatedAt" }, "idx_cases_project_created")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "ProjectId", "Status" }, "idx_cases_project_status")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CaseType" }, "idx_cases_type")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("cases");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("ExpectedCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_completion_date");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("SeUserId")
                        .HasColumnType("integer")
                        .HasColumnName("se_user_id");

                    b.HasKey("AssignmentId")
                        .HasName("case_assignments_pkey");

                    b.HasIndex(new[] { "AssignedBy" }, "idx_assign_by")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CaseId", "IsActive" }, "idx_assign_case")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "SeUserId", "IsActive" }, "idx_assign_se")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("case_assignments");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseEstimation", b =>
                {
                    b.Property<int>("EstimationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("estimation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("EstimationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<int?>("CaseLogId")
                        .HasColumnType("integer")
                        .HasColumnName("case_log_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<short>("EstimationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)10)
                        .HasColumnName("estimation_status");

                    b.Property<int>("EstimatorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("estimator_user_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateOnly?>("ReplyDate")
                        .HasColumnType("date")
                        .HasColumnName("reply_date");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date")
                        .HasColumnName("request_date");

                    b.Property<int>("SeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("seq_no");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EstimationId")
                        .HasName("case_estimations_pkey");

                    b.HasIndex(new[] { "CaseId" }, "idx_est_case")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "EstimatorUserId" }, "idx_est_estimator")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "EstimationStatus" }, "idx_est_status")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("case_estimations");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("LogId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("HandlerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("handler_user_id");

                    b.Property<string>("HandlingMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling_method");

                    b.Property<string>("HandlingResult")
                        .HasColumnType("text")
                        .HasColumnName("handling_result");

                    b.Property<short>("Headcount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("headcount");

                    b.Property<decimal>("HoursSpent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hours_spent");

                    b.Property<DateOnly>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("log_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<short>("StatusAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)30)
                        .HasColumnName("status_after");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LogId")
                        .HasName("case_logs_pkey");

                    b.HasIndex(new[] { "CaseId" }, "idx_logs_case")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "LogDate" }, "idx_logs_date")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "HandlerUserId", "LogDate" }, "idx_logs_handler")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("case_logs");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseReply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reply_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ReplyId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ReplierUserId")
                        .HasColumnType("integer")
                        .HasColumnName("replier_user_id");

                    b.Property<string>("ReplyContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reply_content");

                    b.Property<DateOnly>("ReplyDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("reply_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ReplyId")
                        .HasName("case_replies_pkey");

                    b.HasIndex("ReplierUserId");

                    b.HasIndex(new[] { "CaseId" }, "idx_replies_case")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("case_replies");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CustomerId")
                        .HasName("Customers_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_customers_active")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("read_at");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "CaseId" }, "idx_notif_case")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "RecipientUserId", "IsRead", "CreatedAt" }, "idx_notif_recipient")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.ProblemCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CaseTypeFilter")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("case_type_filter");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CategoryId")
                        .HasName("problem_categories_pkey");

                    b.HasIndex(new[] { "SortOrder", "IsActive" }, "idx_cat_sort")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CategoryName" }, "uk_problem_categories_name")
                        .IsUnique();

                    b.ToTable("problem_categories");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProjectId")
                        .HasName("project_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_projects_active")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CustomerId" }, "idx_projects_customer")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.ProjectMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("member_role")
                        .HasDefaultValueSql("'SE'::character varying");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("MemberId")
                        .HasName("member_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ProjectId", "MemberRole", "IsActive" }, "idx_pm_active")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "ProjectId", "UserId" }, "uk_project_user")
                        .IsUnique()
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("project_members");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.SystemModule", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ModuleId")
                        .HasName("system_modules_pkey");

                    b.HasIndex(new[] { "ProjectId", "ModuleName" }, "uk_project_module")
                        .IsUnique()
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("system_modules");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("GoogleSub")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_sub");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("google_email");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_provider")
                        .HasDefaultValueSql("'local'::character varying");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'SE'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("Users_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_users_active")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Role" }, "idx_users_role")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "GoogleSub" }, "idx_users_google_sub")
                        .IsUnique()
                        .HasFilter("google_sub IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Attachment", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.User", "UploadedByNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("attachments_uploaded_by_fkey");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.AuditLog", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Case", "Case")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CaseId")
                        .HasConstraintName("audit_logs_case_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Case", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.User", "AssignedPm")
                        .WithMany("CaseAssignedPms")
                        .HasForeignKey("AssignedPmId")
                        .HasConstraintName("cases_assigned_pm_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "CancelledByNavigation")
                        .WithMany("CaseCancelledByNavigations")
                        .HasForeignKey("CancelledBy")
                        .HasConstraintName("cases_cancelled_by_fkey");

                    b.HasOne("CaseFlow.Server.Models.ProblemCategory", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("cases_category_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "ClosedByNavigation")
                        .WithMany("CaseClosedByNavigations")
                        .HasForeignKey("ClosedBy")
                        .HasConstraintName("cases_closed_by_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "CreatedByNavigation")
                        .WithMany("CaseCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("cases_created_by_fkey");

                    b.HasOne("CaseFlow.Server.Models.Customer", "Customer")
                        .WithMany("Cases")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("cases_customer_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.SystemModule", "Module")
                        .WithMany("Cases")
                        .HasForeignKey("ModuleId")
                        .HasConstraintName("cases_module_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.Project", "Project")
                        .WithMany("Cases")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("cases_project_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.Case", "RelatedCase")
                        .WithMany("InverseRelatedCase")
                        .HasForeignKey("RelatedCaseId")
                        .HasConstraintName("cases_related_case_id_fkey");

                    b.Navigation("AssignedPm");

                    b.Navigation("CancelledByNavigation");

                    b.Navigation("Category");

                    b.Navigation("ClosedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("Module");

                    b.Navigation("Project");

                    b.Navigation("RelatedCase");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseAssignment", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.User", "AssignedByNavigation")
                        .WithMany("CaseAssignmentAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("case_assignments_assigned_by_fkey");

                    b.HasOne("CaseFlow.Server.Models.Case", "Case")
                        .WithMany("CaseAssignments")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("case_assignments_case_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "SeUser")
                        .WithMany("CaseAssignmentSeUsers")
                        .HasForeignKey("SeUserId")
                        .IsRequired()
                        .HasConstraintName("case_assignments_se_user_id_fkey");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Case");

                    b.Navigation("SeUser");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseEstimation", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Case", "Case")
                        .WithMany("CaseEstimations")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("case_estimations_case_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "EstimatorUser")
                        .WithMany("CaseEstimations")
                        .HasForeignKey("EstimatorUserId")
                        .IsRequired()
                        .HasConstraintName("case_estimations_estimator_user_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("EstimatorUser");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseLog", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Case", "Case")
                        .WithMany("CaseLogs")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("case_logs_case_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "HandlerUser")
                        .WithMany("CaseLogs")
                        .HasForeignKey("HandlerUserId")
                        .IsRequired()
                        .HasConstraintName("case_logs_handler_user_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("HandlerUser");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.CaseReply", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Case", "Case")
                        .WithMany("CaseReplies")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("case_replies_case_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "ReplierUser")
                        .WithMany("CaseReplies")
                        .HasForeignKey("ReplierUserId")
                        .IsRequired()
                        .HasConstraintName("case_replies_replier_user_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("ReplierUser");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Notification", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Case", "Case")
                        .WithMany("Notifications")
                        .HasForeignKey("CaseId")
                        .HasConstraintName("notifications_case_id_fkey");

                    b.HasOne("CaseFlow.Server.Models.User", "RecipientUser")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .IsRequired()
                        .HasConstraintName("notifications_recipient_user_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Project", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_projects_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.ProjectMember", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("fk_member_projects");

                    b.HasOne("CaseFlow.Server.Models.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_member_user");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.SystemModule", b =>
                {
                    b.HasOne("CaseFlow.Server.Models.Project", "Project")
                        .WithMany("SystemModules")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("fk_system_modules_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Case", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CaseAssignments");

                    b.Navigation("CaseEstimations");

                    b.Navigation("CaseLogs");

                    b.Navigation("CaseReplies");

                    b.Navigation("InverseRelatedCase");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Customer", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.ProblemCategory", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.Project", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("ProjectMembers");

                    b.Navigation("SystemModules");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.SystemModule", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("CaseFlow.Server.Models.User", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("CaseAssignedPms");

                    b.Navigation("CaseAssignmentAssignedByNavigations");

                    b.Navigation("CaseAssignmentSeUsers");

                    b.Navigation("CaseCancelledByNavigations");

                    b.Navigation("CaseClosedByNavigations");

                    b.Navigation("CaseCreatedByNavigations");

                    b.Navigation("CaseEstimations");

                    b.Navigation("CaseLogs");

                    b.Navigation("CaseReplies");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
