-- =============================================================================
-- CaseFlow Safe Migration Script
-- Source  : EF Core migration 20260519041519_InitialCreate
-- Target  : PostgreSQL 16 / Cloud SQL
-- Safe    : Production-safe — no DROP, no TRUNCATE, no destructive DDL
--           Every statement is idempotent (IF NOT EXISTS / ON CONFLICT).
--
-- Usage   : psql "host=HOST dbname=postgres user=postgres" -f safe-migration.sql
-- Order   : Run AFTER schema-diagnostic.sql confirms what is missing.
--           Run BEFORE baseline-migrations.sql.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Enable uuid-ossp extension (harmless if already present)
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ===========================================================================
-- SECTION A: Create missing tables (exact DDL from InitialCreate)
-- ===========================================================================
-- Tables are created in dependency order.
-- If a table already exists, CREATE TABLE IF NOT EXISTS is a no-op.
-- ---------------------------------------------------------------------------

-- A1. customers
--     IMPORTANT: PK column is "CustomerId" (PascalCase quoted identifier)
--     because EF Core did not apply snake_case naming to this property.
CREATE TABLE IF NOT EXISTS customers (
    "CustomerId"    INTEGER                     GENERATED BY DEFAULT AS IDENTITY
                                                CONSTRAINT "Customers_pkey" PRIMARY KEY,
    customer_name   CHARACTER VARYING(100)      NOT NULL,
    contact_person  CHARACTER VARYING(100),
    contact_phone   CHARACTER VARYING(30),
    contact_email   CHARACTER VARYING(150),
    address         CHARACTER VARYING(255),
    remarks         TEXT,
    is_active       BOOLEAN                     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

-- A2. problem_categories
CREATE TABLE IF NOT EXISTS problem_categories (
    category_id     INTEGER                     GENERATED BY DEFAULT AS IDENTITY
                                                CONSTRAINT problem_categories_pkey PRIMARY KEY,
    category_name   CHARACTER VARYING(100)      NOT NULL,
    description     CHARACTER VARYING(255),
    sort_order      INTEGER                     NOT NULL,
    case_type_filter CHARACTER VARYING(20),
    is_active       BOOLEAN                     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

-- A3. users
--     must_change_password: migration declares NOT NULL with no default.
--     When adding to an existing table we use DEFAULT FALSE (see Section B).
CREATE TABLE IF NOT EXISTS users (
    user_id              INTEGER                     GENERATED BY DEFAULT AS IDENTITY
                                                     CONSTRAINT "Users_pkey" PRIMARY KEY,
    username             CHARACTER VARYING(50)       NOT NULL,
    password_hash        CHARACTER VARYING(255)      NOT NULL,
    full_name            CHARACTER VARYING(100)      NOT NULL,
    email                CHARACTER VARYING(150)      NOT NULL,
    phone                CHARACTER VARYING(30),
    role                 CHARACTER VARYING(20)       NOT NULL DEFAULT 'SE'::CHARACTER VARYING,
    is_active            BOOLEAN                     NOT NULL DEFAULT TRUE,
    last_login_at        TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    must_change_password BOOLEAN                     NOT NULL DEFAULT FALSE
);

-- A4. projects  (FK → customers."CustomerId")
CREATE TABLE IF NOT EXISTS projects (
    project_id   INTEGER                     GENERATED BY DEFAULT AS IDENTITY
                                             CONSTRAINT project_pkey PRIMARY KEY,
    project_code CHARACTER VARYING(20)       NOT NULL,
    project_name CHARACTER VARYING(100)      NOT NULL,
    customer_id  INTEGER                     NOT NULL,
    description  TEXT,
    start_date   DATE,
    end_date     DATE,
    is_active    BOOLEAN                     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_projects_customer
        FOREIGN KEY (customer_id) REFERENCES customers("CustomerId")
);

-- A5. attachments  (attachment_id = integer IDENTITY ALWAYS)
CREATE TABLE IF NOT EXISTS attachments (
    attachment_id INTEGER                     GENERATED ALWAYS AS IDENTITY
                                              CONSTRAINT attachments_pkey PRIMARY KEY,
    file_name     CHARACTER VARYING(255)      NOT NULL,
    stored_name   CHARACTER VARYING(255)      NOT NULL,
    file_path     CHARACTER VARYING(500)      NOT NULL,
    file_size     INTEGER                     NOT NULL,
    mime_type     CHARACTER VARYING(100)      NOT NULL,
    entity_type   CHARACTER VARYING(50)       NOT NULL,
    entity_id     INTEGER                     NOT NULL,
    uploaded_by   INTEGER                     NOT NULL,
    uploaded_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT attachments_uploaded_by_fkey
        FOREIGN KEY (uploaded_by) REFERENCES users(user_id)
);

-- A6. project_members
--     joined_at = date (DateOnly in C# → date in PG, NOT timestamp)
--     member_role = CHARACTER VARYING with no length limit
CREATE TABLE IF NOT EXISTS project_members (
    member_id   INTEGER  GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT member_pkey PRIMARY KEY,
    project_id  INTEGER  NOT NULL,
    user_id     INTEGER  NOT NULL,
    member_role CHARACTER VARYING   NOT NULL DEFAULT 'SE'::CHARACTER VARYING,
    joined_at   DATE                NOT NULL DEFAULT CURRENT_DATE,
    is_active   BOOLEAN             NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_member_projects
        FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_member_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- A7. system_modules
CREATE TABLE IF NOT EXISTS system_modules (
    module_id   INTEGER                     GENERATED BY DEFAULT AS IDENTITY
                                            CONSTRAINT system_modules_pkey PRIMARY KEY,
    project_id  INTEGER                     NOT NULL,
    module_name CHARACTER VARYING(100)      NOT NULL,
    description CHARACTER VARYING(255),
    is_active   BOOLEAN                     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_system_modules_project
        FOREIGN KEY (project_id) REFERENCES projects(project_id)
);

-- A8. cases
--     case_id = integer IDENTITY ALWAYS
--     category_id NOT NULL (migration: nullable:false)
--     reporter_name NOT NULL (migration: nullable:false)
--     total_hours = numeric(7,2) NOT NULL
CREATE TABLE IF NOT EXISTS cases (
    case_id         INTEGER                     GENERATED ALWAYS AS IDENTITY
                                                CONSTRAINT cases_pkey PRIMARY KEY,
    case_number     CHARACTER VARYING(30)       NOT NULL,
    project_id      INTEGER                     NOT NULL,
    customer_id     INTEGER                     NOT NULL,
    category_id     INTEGER                     NOT NULL,
    module_id       INTEGER,
    reporter_name   CHARACTER VARYING(100)      NOT NULL,
    reporter_phone  CHARACTER VARYING(30),
    reporter_email  CHARACTER VARYING(150),
    case_type       CHARACTER VARYING(20)       NOT NULL DEFAULT 'REPAIR'::CHARACTER VARYING,
    priority        CHARACTER VARYING(10)       NOT NULL DEFAULT 'MEDIUM'::CHARACTER VARYING,
    description     TEXT                        NOT NULL,
    status          SMALLINT                    NOT NULL DEFAULT 10,
    created_by      INTEGER                     NOT NULL,
    assigned_pm_id  INTEGER,
    closed_by       INTEGER,
    cancelled_by    INTEGER,
    related_case_id INTEGER,
    relation_type   CHARACTER VARYING(20),
    closed_at       TIMESTAMP WITHOUT TIME ZONE,
    cancelled_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    total_hours     NUMERIC(7,2)                NOT NULL DEFAULT 0,
    CONSTRAINT cases_assigned_pm_id_fkey
        FOREIGN KEY (assigned_pm_id) REFERENCES users(user_id),
    CONSTRAINT cases_cancelled_by_fkey
        FOREIGN KEY (cancelled_by) REFERENCES users(user_id),
    CONSTRAINT cases_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES problem_categories(category_id),
    CONSTRAINT cases_closed_by_fkey
        FOREIGN KEY (closed_by) REFERENCES users(user_id),
    CONSTRAINT cases_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT cases_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES customers("CustomerId"),
    CONSTRAINT cases_module_id_fkey
        FOREIGN KEY (module_id) REFERENCES system_modules(module_id),
    CONSTRAINT cases_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT cases_related_case_id_fkey
        FOREIGN KEY (related_case_id) REFERENCES cases(case_id)
);

-- A9. audit_logs  (audit_id = bigint IDENTITY ALWAYS)
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id    BIGINT                      GENERATED ALWAYS AS IDENTITY
                                            CONSTRAINT audit_logs_pkey PRIMARY KEY,
    user_id     INTEGER                     NOT NULL,
    case_id     INTEGER,
    action      CHARACTER VARYING(100)      NOT NULL,
    entity_type CHARACTER VARYING(50),
    entity_id   INTEGER,
    old_value   JSONB,
    new_value   JSONB,
    ip_address  CHARACTER VARYING(45),
    user_agent  CHARACTER VARYING(500),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_case_id_fkey
        FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT audit_logs_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- A10. case_assignments
CREATE TABLE IF NOT EXISTS case_assignments (
    assignment_id            INTEGER  GENERATED ALWAYS AS IDENTITY
                                      CONSTRAINT case_assignments_pkey PRIMARY KEY,
    case_id                  INTEGER  NOT NULL,
    se_user_id               INTEGER  NOT NULL,
    assigned_by              INTEGER  NOT NULL,
    is_primary               BOOLEAN  NOT NULL,
    instructions             TEXT,
    expected_completion_date DATE,
    is_active                BOOLEAN  NOT NULL DEFAULT TRUE,
    assigned_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT case_assignments_assigned_by_fkey
        FOREIGN KEY (assigned_by) REFERENCES users(user_id),
    CONSTRAINT case_assignments_case_id_fkey
        FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT case_assignments_se_user_id_fkey
        FOREIGN KEY (se_user_id) REFERENCES users(user_id)
);

-- A11. case_estimations
--      case_log_id: integer nullable, NO FK constraint in migration
CREATE TABLE IF NOT EXISTS case_estimations (
    estimation_id     INTEGER      GENERATED ALWAYS AS IDENTITY
                                   CONSTRAINT case_estimations_pkey PRIMARY KEY,
    case_id           INTEGER      NOT NULL,
    estimator_user_id INTEGER      NOT NULL,
    seq_no            INTEGER      NOT NULL,
    request_date      DATE         NOT NULL,
    summary           TEXT         NOT NULL,
    estimated_hours   NUMERIC(6,2) NOT NULL,
    reply_date        DATE,
    estimation_status SMALLINT     NOT NULL DEFAULT 10,
    remarks           TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    case_log_id INTEGER,
    CONSTRAINT case_estimations_case_id_fkey
        FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT case_estimations_estimator_user_id_fkey
        FOREIGN KEY (estimator_user_id) REFERENCES users(user_id)
);

-- A12. case_logs
CREATE TABLE IF NOT EXISTS case_logs (
    log_id          INTEGER      GENERATED ALWAYS AS IDENTITY
                                 CONSTRAINT case_logs_pkey PRIMARY KEY,
    case_id         INTEGER      NOT NULL,
    handler_user_id INTEGER      NOT NULL,
    log_date        DATE         NOT NULL DEFAULT CURRENT_DATE,
    handling_method TEXT         NOT NULL,
    handling_result TEXT,
    hours_spent     NUMERIC(6,2) NOT NULL,
    headcount       SMALLINT     NOT NULL DEFAULT 1,
    status_after    SMALLINT     NOT NULL DEFAULT 30,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT case_logs_case_id_fkey
        FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT case_logs_handler_user_id_fkey
        FOREIGN KEY (handler_user_id) REFERENCES users(user_id)
);

-- A13. case_replies
CREATE TABLE IF NOT EXISTS case_replies (
    reply_id        INTEGER  GENERATED ALWAYS AS IDENTITY
                             CONSTRAINT case_replies_pkey PRIMARY KEY,
    case_id         INTEGER  NOT NULL,
    replier_user_id INTEGER  NOT NULL,
    reply_date      DATE     NOT NULL DEFAULT CURRENT_DATE,
    reply_content   TEXT     NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT case_replies_case_id_fkey
        FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT case_replies_replier_user_id_fkey
        FOREIGN KEY (replier_user_id) REFERENCES users(user_id)
);

-- A14. notifications
CREATE TABLE IF NOT EXISTS notifications (
    notification_id   INTEGER                     GENERATED ALWAYS AS IDENTITY
                                                  CONSTRAINT notifications_pkey PRIMARY KEY,
    recipient_user_id INTEGER                     NOT NULL,
    case_id           INTEGER,
    notification_type CHARACTER VARYING(50)       NOT NULL,
    title             CHARACTER VARYING(200)      NOT NULL,
    message           TEXT                        NOT NULL,
    is_read           BOOLEAN                     NOT NULL,
    read_at           TIMESTAMP WITHOUT TIME ZONE,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT notifications_case_id_fkey
        FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT notifications_recipient_user_id_fkey
        FOREIGN KEY (recipient_user_id) REFERENCES users(user_id)
);

-- ===========================================================================
-- SECTION B: Add missing columns to existing tables (ALTER only when needed)
-- ===========================================================================
-- These are the columns most likely to be absent when the DB was created
-- from an earlier version of the schema (before InitialCreate was finalised).
-- Each ALTER TABLE ... ADD COLUMN IF NOT EXISTS is idempotent.
-- ---------------------------------------------------------------------------

-- B1. users.must_change_password
--     Migration declares NOT NULL with no default, but we must supply DEFAULT
--     FALSE here so that existing rows get a value during the column addition.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

-- B2. cases.total_hours
ALTER TABLE cases
    ADD COLUMN IF NOT EXISTS total_hours NUMERIC(7,2) NOT NULL DEFAULT 0;

-- B3. case_estimations.case_log_id
ALTER TABLE case_estimations
    ADD COLUMN IF NOT EXISTS case_log_id INTEGER;

-- ===========================================================================
-- SECTION C: Indexes  (44 indexes from InitialCreate, all IF NOT EXISTS)
-- ===========================================================================

-- attachments
CREATE INDEX IF NOT EXISTS idx_attach_entity
    ON attachments (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_attach_uploader
    ON attachments (uploaded_by);

-- audit_logs
CREATE INDEX IF NOT EXISTS idx_audit_action
    ON audit_logs (action, created_at);

CREATE INDEX IF NOT EXISTS idx_audit_case
    ON audit_logs (case_id);

CREATE INDEX IF NOT EXISTS idx_audit_entity
    ON audit_logs (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_user
    ON audit_logs (user_id, created_at);

-- case_assignments
CREATE INDEX IF NOT EXISTS idx_assign_by
    ON case_assignments (assigned_by);

CREATE INDEX IF NOT EXISTS idx_assign_case
    ON case_assignments (case_id, is_active);

CREATE INDEX IF NOT EXISTS idx_assign_se
    ON case_assignments (se_user_id, is_active);

-- case_estimations
CREATE INDEX IF NOT EXISTS idx_est_case
    ON case_estimations (case_id);

CREATE INDEX IF NOT EXISTS idx_est_estimator
    ON case_estimations (estimator_user_id);

CREATE INDEX IF NOT EXISTS idx_est_status
    ON case_estimations (estimation_status);

-- case_logs
CREATE INDEX IF NOT EXISTS idx_logs_case
    ON case_logs (case_id);

CREATE INDEX IF NOT EXISTS idx_logs_date
    ON case_logs (log_date);

CREATE INDEX IF NOT EXISTS idx_logs_handler
    ON case_logs (handler_user_id, log_date);

-- case_replies
CREATE INDEX IF NOT EXISTS idx_replies_case
    ON case_replies (case_id);

CREATE INDEX IF NOT EXISTS "IX_case_replies_replier_user_id"
    ON case_replies (replier_user_id);

-- cases
CREATE UNIQUE INDEX IF NOT EXISTS cases_case_number_key
    ON cases (case_number);

CREATE INDEX IF NOT EXISTS idx_cases_assigned_pm
    ON cases (assigned_pm_id);

CREATE INDEX IF NOT EXISTS idx_cases_category
    ON cases (category_id);

CREATE INDEX IF NOT EXISTS idx_cases_created_at
    ON cases (created_at);

CREATE INDEX IF NOT EXISTS idx_cases_created_by
    ON cases (created_by);

CREATE INDEX IF NOT EXISTS idx_cases_customer
    ON cases (customer_id);

CREATE INDEX IF NOT EXISTS idx_cases_priority
    ON cases (priority);

CREATE INDEX IF NOT EXISTS idx_cases_project_created
    ON cases (project_id, created_at);

CREATE INDEX IF NOT EXISTS idx_cases_project_status
    ON cases (project_id, status);

CREATE INDEX IF NOT EXISTS idx_cases_type
    ON cases (case_type);

CREATE INDEX IF NOT EXISTS "IX_cases_cancelled_by"
    ON cases (cancelled_by);

CREATE INDEX IF NOT EXISTS "IX_cases_closed_by"
    ON cases (closed_by);

CREATE INDEX IF NOT EXISTS "IX_cases_module_id"
    ON cases (module_id);

CREATE INDEX IF NOT EXISTS "IX_cases_related_case_id"
    ON cases (related_case_id);

-- customers
CREATE INDEX IF NOT EXISTS idx_customers_active
    ON customers (is_active);

-- notifications
CREATE INDEX IF NOT EXISTS idx_notif_case
    ON notifications (case_id);

CREATE INDEX IF NOT EXISTS idx_notif_recipient
    ON notifications (recipient_user_id, is_read, created_at);

-- problem_categories
CREATE INDEX IF NOT EXISTS idx_cat_sort
    ON problem_categories (sort_order, is_active);

CREATE UNIQUE INDEX IF NOT EXISTS uk_problem_categories_name
    ON problem_categories (category_name);

-- project_members
CREATE INDEX IF NOT EXISTS idx_pm_active
    ON project_members (project_id, member_role, is_active);

CREATE INDEX IF NOT EXISTS "IX_project_members_user_id"
    ON project_members (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_project_user
    ON project_members (project_id, user_id);

-- projects
CREATE INDEX IF NOT EXISTS idx_projects_active
    ON projects (is_active);

CREATE INDEX IF NOT EXISTS idx_projects_customer
    ON projects (customer_id);

-- system_modules
CREATE UNIQUE INDEX IF NOT EXISTS uk_project_module
    ON system_modules (project_id, module_name);

-- users
CREATE INDEX IF NOT EXISTS idx_users_active
    ON users (is_active);

CREATE INDEX IF NOT EXISTS idx_users_role
    ON users (role);

-- ===========================================================================
COMMIT;
-- ===========================================================================

\echo 'safe-migration.sql complete.'

-- Verification: show column count per table
SELECT table_name, COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN (
    'customers','problem_categories','users','projects','attachments',
    'project_members','system_modules','cases','audit_logs',
    'case_assignments','case_estimations','case_logs','case_replies','notifications'
  )
GROUP BY table_name
ORDER BY table_name;
